version: "3.8"

services:
  server1:
    build: .
    container_name: ubuntu1
    ports:
      - "2221:22"

  server2:
    build: .
    container_name: ubuntu2
    ports:
      - "2222:22"

  server3:
    build: .
    container_name: ubuntu3
    ports:
      - "2223:22"

  server4:
    build: .
    container_name: ubuntu4
    ports:
      - "2224:22"

  server5:
    build: .
    container_name: ubuntu5
    ports:
      - "2225:22"
